// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNameList(arg1:string):Promise<Array<string>>;

export function RandomName():Promise<string>;
